### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by meetkoriya13** [karankraina/tic-tac-toe#1]
# Your project is not working, i wanted to play tic-tac-toe so much but couldn't able to very disappointed.

![image](https://github.com/user-attachments/assets/e751b475-ac80-4201-83cc-a3283dc139c0)

**Comment by meetkoriya13** [comment]
@karankraina Please fix this ASAP

**Comment by meetkoriya13** [comment]
Working now bro @karankraina 
but please add proper steps on readme for how to setup.

also add some message when game draws
![image](https://github.com/user-attachments/assets/308fa92f-5767-473f-becb-c19de9d6572e)

Thank you in advance

**Comment by meetkoriya13** [comment]
@karankraina You are noooob, application is running on 8080 but 3000 port is being consoled in terminal. fix ASAP

**Comment by karankraina** [comment]
Fixed bro @meetkoriya13 . Chill
